services:

  loki:
    container_name: loki
    image: grafana/loki:3.3.2
    user: "0"
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - ./.data/loki/data:/loki
      - ./.data/loki/wal:/wal

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    user: "${UID}:${GID}"
    restart: unless-stopped
    ports: ["9090:9090"]
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./.data/prometheus:/prometheus

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    user: "${UID}:${GID}"
    restart: unless-stopped
    ports: ["3000:3000"]
    environment:
      GF_SECURITY_ADMIN_USER: ${PROD_DASH_GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${PROD_DASH_GRAFANA_ADMIN_PASS}
    volumes:
      - ./.data/grafana:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning
      - ./config/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on: [prometheus]

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:9.2.0
    restart: unless-stopped
    environment:
      ELASTICSEARCH_HOSTS: "https://${PROD_ELASTICSEARCH_HOST}:${PROD_ELASTICSEARCH_PORT}" # "https://${10.92.36.18}:9203" # "https://10.95.35.1:9200" # 
      ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES: /usr/share/kibana/config/certs/graph-es-prod-xaas-ca.crt
      ELASTICSEARCH_SSL_VERIFICATIONMODE: none
      ELASTICSEARCH_SERVICEACCOUNTTOKEN: ${PROD_DASH_KIBANA_SRVTOKEN}
      SERVER_PORT: 5604
    ports: ["5604:5604"]
    volumes:
      - ./.certs:/usr/share/kibana/config/certs:ro
      - ./.data/kibana:/usr/share/kibana/data

  postgres:
    container_name: infisical-postgres
    image: postgres:16
    user: "${UID}:${GID}"
    restart: always
    environment:
      POSTGRES_USER: ${PROD_DASH_POSTGRES_INFISICAL_USER}
      POSTGRES_PASSWORD: ${PROD_DASH_POSTGRES_INFISICAL_PASS}
      POSTGRES_DB: infisical_db
    volumes:
      - infisical-db-bind:/var/lib/postgresql/data

  redis:
    container_name: infisical-redis
    image: redis:7
    user: "${UID}:${GID}"
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - infisical-redis-bind:/data

  infisical:
    image: infisical/infisical:latest
    container_name: infisical
    restart: always
    depends_on:
      - postgres
      - redis
    # Infisical listens on 8080 inside the container by default
    ports:
      - "8648:8080"
    env_file: .env
    environment:
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      AUTH_SECRET: ${AUTH_SECRET}
      DB_CONNECTION_URI: postgresql://${PROD_DASH_POSTGRES_INFISICAL_USER}:${PROD_DASH_POSTGRES_INFISICAL_PASS}@postgres:5432/infisical_db
      REDIS_URL: redis://redis:6379
      SITE_URL: https://${DASH_HOST}:8651
      HOST: 0.0.0.0
      PORT: 8080
      INFISICAL_DISABLE_UPDATE_CHECK: "true"

  infisical-nginx:
    image: nginx:1.27
    container_name: infisical-nginx
    restart: unless-stopped
    depends_on:
      - infisical
    ports:
      - "8650:80"         # VERY IMPORTANT: no TLS yet
    volumes:
      - ./nginx.infisical.conf:/etc/nginx/conf.d/default.conf:ro

  infisical-nginx-https:
    image: nginx:1.27
    container_name: infisical-nginx-https
    restart: unless-stopped
    depends_on:
      - infisical
    ports:
      - "8651:443"
    volumes:
      - ./nginx.infisical-https.conf:/etc/nginx/conf.d/default.conf:ro
      - /home/dockerhost/.certs/infisical.crt:/etc/nginx/certs/infisical.crt:ro
      - /home/dockerhost/.certs/infisical.key:/etc/nginx/certs/infisical.key:ro

  dashy:
    image: lissy93/dashy:latest
    container_name: dashy
    restart: unless-stopped
    ports:
      - "4000:8080"
    volumes:
      - ./config/dashy/config.yml:/app/user-data/conf.yml
      - ./config/dashy/icons:/app/user-data/item-icons

  dashy-nginx-https:
    image: nginx:1.27
    container_name: dashy-nginx-https
    restart: unless-stopped
    depends_on:
      - dashy
    ports:
      - "8443:443"   # HTTPS for Dashy
    volumes:
      - ./nginx.dashy-https.conf:/etc/nginx/conf.d/default.conf:ro
      - /home/dockerhost/.certs/infisical.crt:/etc/nginx/certs/infisical.crt:ro
      - /home/dockerhost/.certs/infisical.key:/etc/nginx/certs/infisical.key:ro      

volumes:

  infisical-db-bind:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./.data/infisical/postgres

  infisical-redis-bind:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./.data/infisical/redis
