global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: "rcp-remote"
    role: "monitor-client"

scrape_configs:
  - job_name: 'celery'
    static_configs:
      - targets: ['10.92.36.18:9808']
        labels: { service: 'celery' }

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['10.92.36.18:15672']
        labels: { service: 'rabbitmq' }

  - job_name: 'docker'
    static_configs:
      - targets: ['10.92.36.18:9417']
        labels: { service: 'docker-stats-exporter' }

  - job_name: 'gpu'
    static_configs:
      - targets: ['10.92.36.18:9400']
        labels: { service: 'nvidia-gpu' }